[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Ernest"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
advent-of-code-data = "^2.1.0"
numpy = "^2.3.5"
matplotlib = "^3.10.7"
poetry-core = "^2.2.1"


[tool.poetry.group.dev.dependencies]
scikit-spatial = "^9.0.1"
pre-commit = "^4.5.0"
black = "^25.11.0"
commitizen = "^4.10.0"
mypy = "^1.19.0"


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
